#ifndef CUSTOM_KEYCODES_DERUI_H
#define CUSTOM_KEYCODES_DERUI_H

#define KC_JA_HAT KC_EQL
#define KC_JA_AT KC_LBRC
#define KC_JA_CLN KC_QUOT
#define KC_JA_RBRC KC_BSLS
#define KC_JA_LBRC KC_RBRC

enum custom_keycodes {
  QWERTY = SAFE_RANGE,
  LOWER,
  RAISE,
  ADJUST,
  KC_NN_SHIFT,
  KC_NN_LSHIFT,
  KC_NN_RSHIFT,
  M_SKK_STICKY,
  M_LOWER_SKK_STICKY,
  M_RAISE_SKK_STICKY,
  M_EISU,
  M_KANA,
  M_LALT,
  M_RALT,
  M_JAPAN_ROMA,
  M_JAPAN_KANA,
  M_GAMING,
  M_ENABLE_MAC,
  M_DISABLE_MAC,
  M_LSFT_LGUI,
  M_RSFT_RGUI,
  M_LOWER_EISU,
  M_RAISE_KANA,
  M_RAISE_TAB
};

#endif
